# Generated by Django 4.0.4 on 2023-01-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_club_owner',
            field=models.BooleanField(default=False, verbose_name='club owner status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_pro_member',
            field=models.BooleanField(default=False, verbose_name='pro member status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_standard_member',
            field=models.BooleanField(default=False, verbose_name='standard member status'),
        ),
    ]
