# Generated by Django 4.0.4 on 2023-01-31 23:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_is_club_owner_user_is_pro_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.FloatField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
