# Generated by Django 4.0.4 on 2023-01-19 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(max_length=100)),
                ('discount_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discounts.discount')),
            ],
        ),
    ]
