# Generated by Django 4.0.4 on 2023-01-26 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='address_id',
            new_name='address',
        ),
        migrations.AddField(
            model_name='tournament',
            name='end_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='player_count',
            field=models.IntegerField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
